sonar.projectKey=mk-store
sonar.projectName=mk-store
sonar.sources=backend,frontend/src
sonar.tests=backend
sonar.test.inclusions=backend/**/*_test.go
sonar.exclusions=**/*.gen.go,**/node_modules/**,**/dist/**,**/.terraform/**
sonar.go.coverage.reportPaths=backend/coverage.out
