apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mk-store-backend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - mk-store
  selector:
    matchLabels:
      app: mk-store-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
