apiVersion: v1
kind: ConfigMap
metadata:
  name: mk-store-grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  mk-store-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        editable: false
